### ISSUE TITLE
Odd Accordion behaviour

### ISSUE THREAD

**Issue by nickcolley** [alphagov/frontend#1054]
Issue found while visiting the Scottish Government's Device Lab

We seem to be changing behaviour based on JavaScript events firing which does not work in all scenarios

https://youtu.be/hAW6V3seuy8

Also see video of a Galaxy Tab 2 with an odd jumping behaviour

https://drive.google.com/file/d/0B-GzTJBVVSNzWTN5X2hKN0pZLWs/view

As seen on https://www.gov.uk/employer-recruitment-incentive-scotland

**Comment by tijmenb** [comment]
The business support pages were moved last year to government-frontend and don't use the accordion anymore.

Example: https://www.gov.uk/business-finance-support/access-to-finance-advice-north-west-england

That means this issue is fixed, please reopen if that's not the case.
