### ISSUE TITLE
Start button padding incorrect on smaller viewports

### ISSUE THREAD

**Issue by nickcolley** [alphagov/frontend#1055]
Issue found while visiting the Scottish Government's Device Lab

![screen shot 2016-11-21 at 22 09 10](https://cloud.githubusercontent.com/assets/2445413/20502706/38fc6dd8-b037-11e6-97c9-b1ee4de20871.png)

As seen on https://www.gov.uk/employer-recruitment-incentive-scotland

**Comment by tijmenb** [comment]
The business support pages were moved last year to government-frontend and are now using the button component. This is fixed now!
