### ISSUE TITLE
Flash of Original Content (and unstyled)

### ISSUE THREAD

**Issue by NickColley** [alphagov/frontend#1056]
Issue found while visiting the Scottish Government's Device Lab

https://youtu.be/JEepIBXFbjQ

We found this kind of issue across the slower devices, I've reproduced this for this example by throttling the CPU, below you can see it spends ~1.2s in JavaScript that we're using to enhance the page.

![screen shot 2016-11-21 at 22 15 49](https://cloud.githubusercontent.com/assets/2445413/20502942/51e058d6-b038-11e6-904b-8acb703bbbff.png)
![screen shot 2016-11-21 at 22 16 28](https://cloud.githubusercontent.com/assets/2445413/20502940/51d900a4-b038-11e6-8db4-3853f4540f96.png)
![screen shot 2016-11-21 at 22 16 16](https://cloud.githubusercontent.com/assets/2445413/20502941/51dcb564-b038-11e6-9c61-d357a55e2df7.png)

To see an example 'for realsies' see https://github.com/alphagov/manuals-frontend/issues/187

**Comment by tijmenb** [comment]
@nickcolley do you remember if this issue is particular to certain pages, or all of the pages?

**Comment by nickcolley** [comment]
This will still be an issue since the tabs have not changed.

We were hoping to iterate the start pages to allow us to remove tabs, but this did not happen.

I think we need to improve our tabs so that they're up to scratch (accessibility too) if there is no planned start page work for a while.

**Comment by hannako** [comment]
Closing this issue as it's very out of day. For example work was done to improve page load times - see blog post by Matt Hobbs here: https://insidegovuk.blog.gov.uk/2022/06/13/what-weve-learned-from-one-year-of-real-user-monitoring-data-on-gov-uk/

Also the example given is manuals frontend which has been retired.
