### ISSUE TITLE
Homepage: Promo headings get repeated

### ISSUE THREAD

**Issue by selfthinker** [alphagov/frontend#1059]
The promo headings on the homepage ([source](https://github.com/alphagov/frontend/blob/master/app/views/homepage/index.html.erb#L163-L189])) get repeated on Assistive Technology because the decorative images have the very same `alt` parameter as the `h3` directly underneath. Ideally the `alt` parameter should be empty but cannot be as it's surrounded by a link.

Removing the link and emptying the `alt` parameter would fix that. Having a link around the image seems to be a deliberate decision, so another fix could be to add the `h3` to the link. So, `<a><img /><h3 /></a>`. There might be other solutions.

**Comment by fofr** [comment]
+1 for moving heading into link

**Comment by tijmenb** [comment]
I think https://github.com/alphagov/frontend/pull/1313 has fixed this issue. Please reopen if that's not the case.
