### ISSUE TITLE
Start page layout slightly broken with no-js and mobile

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/frontend#1206]
# What's wrong
On mobile devices, the start page layout is slightly broken without js.

Tested on Mac OS

Screenshots
![screen shot 2017-04-11 at 12 03 32](https://cloud.githubusercontent.com/assets/2204224/24906261/f0899396-1eae-11e7-9ba9-7a3dd645ac27.png)

**Comment by tijmenb** [comment]
Thanks @edwardhorsford. I'm moving this to a central Trello for prioritisation: https://trello.com/c/yAT7LZ6G/44-start-pages-tabs-dont-work-on-mobile.
