### ISSUE TITLE
version of phantomjs is out of date

### ISSUE THREAD

**Issue by mcgoooo** [alphagov/frontend#1241]
The version of phantomjs (1.9x) is out of date and no longer supported, we should look at upgrading

https://github.com/ariya/phantomjs/

outside the vm, this causes the tests to be non runnable, as phantomjs 1.9x segfaults on sierra (macos) and above

https://github.com/ariya/phantomjs/issues/14558

**Comment by tijmenb** [comment]
Now being tracked here: https://trello.com/c/vfrnbD8a/52-use-replacement-for-phantomjs
