### ISSUE TITLE
Homepage navigation links misaligned

### ISSUE THREAD

**Issue by fofr** [alphagov/frontend#1255]
Homepage navigation links are misaligned following updates to education item. (Only in variant B of currently running AB test)

## Bug
![screen shot 2017-06-23 at 16 46 51](https://user-images.githubusercontent.com/319055/27489795-ce3511c6-5833-11e7-8d4f-7ff349db6a9e.png)

## Bug on iPad
![screen shot 2017-06-23 at 16 50 57](https://user-images.githubusercontent.com/319055/27489902-2a1523c8-5834-11e7-845c-6fcc494563de.png)

## Before
http://webarchive.nationalarchives.gov.uk/20170118110517/https://www.gov.uk/
![screen shot 2017-06-23 at 16 49 11](https://user-images.githubusercontent.com/319055/27489820-eee8f05e-5833-11e7-9eef-3c9e21b3044f.png)

**Comment by tijmenb** [comment]
The A/B tests have concluded and the older items have been put back, so this issue has been resolved.
