### ISSUE TITLE
'Popular on GOV.UK' on the home page is too small

### ISSUE THREAD

**Issue by joelanman** [alphagov/frontend#1268]
'Popular on GOV.UK' is 14px, dropping to 12px on mobile. Our own guidance on font sizes is [not to go below 16px unless there's a user need](https://govuk-elements.herokuapp.com/typography/#typography-body-copy)

Suggest we go to at least 16px.

**Comment by fofr** [comment]
Specifically the heading, not the list below it:

![screen shot 2017-08-09 at 14 12 40](https://user-images.githubusercontent.com/319055/29123207-d7ef352c-7d0c-11e7-8da1-fe8b74ed7d56.png)
