### ISSUE TITLE
task list component spacing breakpoints not aligned with grid

### ISSUE THREAD

**Issue by nickcolley** [alphagov/frontend#1305]
Noticed this while testing our prototype, we're using this page as the start of the journey.

Seen on https://www.gov.uk/view-driving-licence

I think maybe the margins added need to have the same breakpoints as the grid

![image](https://user-images.githubusercontent.com/2445413/32509612-b2585e90-c3e5-11e7-93f3-2742a56a4403.png)

**Comment by andysellick** [comment]
This seems to be a problem for pages in frontend, but works fine on pages in government-frontend. Are our breakpoints different across applications @nickcolley? Please say no..

**Comment by nickcolley** [comment]
Well, alphagov/frontend does use the old 'wrapper' layout which doesnt use the new grid. So it's possible.

**Comment by tijmenb** [comment]
Looks like the step by step is no longer on these pages so we can't see if this is still the case. I'm assuming this will be picked up once new step by steps are created.
