### ISSUE TITLE
 Convert tests from Minitest to RSpec

### ISSUE THREAD

**Issue by huwd** [alphagov/frontend#2669]
## Issue

We are currently migrating GOV.UK accounts from a transition-checker specific feature to something GOV.UK wide.
As such, creating, deleting and callbacks for a session sit more sensibly in a govuk-wide repository like `frontend`, instead of the more specific `finder-frontend`. This change is outlined in [RFC 134](https://github.com/alphagov/govuk-rfcs/pull/134).

- We already have a some [request](https://github.com/alphagov/finder-frontend/blob/release_2112/spec/requests/sessions_spec.rb) and [feature](https://github.com/alphagov/finder-frontend/blob/master/spec/features/brexit_checker/accounts_spec.rb) specs in finder-frontend. It would be nice to re-use these instead of rewrite them in a testing framework that is not the GDS ruby tool [of choice](https://gds-way.cloudapps.digital/manuals/programming-languages/ruby.html#conventional-tooling).
- @hannako has set out a clear approach we can emulate [in collections](https://github.com/alphagov/collections/issues/2259), so there is precident for this shift.
- Like the collections issue we would also be interested in adding Pact Tests to meet GOV.UK's CD requirements as we add this new complexity

## Scale

```
➜  frontend git:(master) rails stats
+----------------------+--------+--------+---------+---------+-----+-------+
| Name                 |  Lines |    LOC | Classes | Methods | M/C | LOC/M |
+----------------------+--------+--------+---------+---------+-----+-------+
| Controllers          |    806 |    641 |      15 |      88 |   5 |     5 |
| Helpers              |     99 |     87 |       0 |      14 |   0 |     4 |
| Models               |    330 |    269 |      13 |      51 |   3 |     3 |
| JavaScripts          |    381 |    160 |       0 |      25 |   0 |     4 |
| Libraries            |    748 |    638 |      15 |      71 |   4 |     6 |
| Integration tests    |   4551 |   3840 |      18 |       2 |   0 |  1918 |
+----------------------+--------+--------+---------+---------+-----+-------+
| Total                |   6915 |   5635 |      61 |     251 |   4 |    20 |
+----------------------+--------+--------+---------+---------+-----+-------+
```

## Approach
- Mirror the work [in collections](https://github.com/alphagov/collections/issues/2259).
- Bring in rspec as a depenency, This will mean Frontend runs two test suites, Minitest and RSpec. 
- Similar to [smart answers](https://github.com/alphagov/smart-answers/) we would run these side by side initially
- That would unblock the Accounts work, allowing us to port over existing accounts tests
- Then we make a list of all unmigrated tests here, and begin working down the list. Starting with [a conversion](https://github.com/alphagov/collections/blob/master/lib/minitest_to_rspec/convert_to_rspec.rb) and then proofing through tests from there

## What would need to be converted:

There is a [rake task](https://github.com/alphagov/collections/blob/e5b305b7e7b3eae0020eed90987ea0abc83bb33d/lib/tasks/converter.rake) that can be used to do some of the syntax conversion. We could begin by bringing that over here.

#### Convert the following
- [ ] test/functional (12 test files)
- [ ] test/integration (18 test files)
- [ ] test/routing (1 test file)
- [ ] test/support (6 helpers)
- [ ] test/unit (14 test files)
- [ ] test/unit/models (2 test files)
- [ ] test/unit/presenters (12 test files)
- [ ] test/unit/services (2 test files)
- [ ] test/unit/simple_smart_answers (2 test files)

**Comment by hannako** [comment]
Closing this issue as the benefits of converting to RSpec do not justify the time it took to complete the conversion.
