### ISSUE TITLE
GA cookies not removed when user opts-out

### ISSUE THREAD

**Issue by neilha** [alphagov/frontend#3733]
## What
Checking "Do not use cookies that measure my website use" and saving changes on the [GOV.UK cookie settings page](https://www.gov.uk/help/cookies) does not remove all Google Analytics cookies.

![image](https://github.com/alphagov/frontend/assets/13355778/ba7599d1-6508-4788-a0e4-1a7a6e393212)

**Comment by andysellick** [comment]
Some work was recently done on this. Based on a brief test on the live site it looks like this issue has been resolved. Accepting all cookies with the cookie banner, then changing consent on the cookies page to reject everything results in the GA cookies being removed from my browser (note: testing this in Chrome the list of cookies doesn't always auto-update, if you click away from the item shown in the screenshot, then back again, it should refresh).

Also just as an assurance even if the GA cookies persist, tracking does not occur if consent has been withdrawn.
