### ISSUE TITLE
"Bad request - 400" on search for %

### ISSUE THREAD

**Issue by edent** [alphagov/frontend#734]
The URL https://www.gov.uk/search?q=20%+tax+rate results in the error `Bad request`.

When using the search box, the `%` is correctly escaped to `%25`.  If the URL is manipulated directly - or a site links to it incorrectly, an error will be displayed.

Any URL with a raw `%` in it will cause this error.

Additionally, while the page title says "Bad Request - 400", an `HTTP 200 OK` is returned by the server.

**Comment by rboulton** [comment]
I think a `Bad Request` status response is appropriate here: the "%+" sequence is an invalid encoding in the query string. We can't easily and safely guess the correct decoded form in all such situations.  (For example, we also return a `Bad Request` status for invalid UTF8 %-encoded values.)

If an external site links to these search results incorrectly, the fix really needs to be done on that site.

I tested this url, and it returns a `HTTP 400` status code for me:

![image](https://cloud.githubusercontent.com/assets/73564/5853793/ec38730c-a21e-11e4-8b25-43b26069977d.png)

Can you give details of why you think the server is returning `HTTP 200 OK` for this request?  If we can reproduce that, it certainly needs fixing.

**Comment by edent** [comment]
Ah, sorry, `wget` automatically fixes the `%`.  You are right that an `HTTP/1.1 400 Bad Request` is correctly returned.

I would perhaps suggest a slightly more friendly error message rather than trying to guess the encoded value?
