### ISSUE TITLE
Error on unknown postcode could be improved

### ISSUE THREAD

**Issue by dracos** [alphagov/frontend#788]
If a postcode is entered that is not recognised on e.g. https://www.gov.uk/report-pothole, the error message is “Please enter a valid full UK postcode.” (source https://github.com/alphagov/frontend/blob/master/app/views/root/_location_form.html.erb#L12)

Given there will always be brand new postcodes that have not yet entered the database, or worse if the database of postcodes has not been kept up to date, this error could read rather poorly to someone who knows full well they have entered a valid full UK postcode.

I would suggest something more friendly, along the lines of “we don't recognise your postcode” or “we can't find your postcode” with suggestions as to what could have gone wrong (mistyping, new/changed postcode, etc), putting the issue on the site rather than the user.

**Comment by RosalynV** [comment]
I've logged this issue it in the relevant [improvement plan](https://insidegovuk.blog.gov.uk/2015/03/13/introducing-improvement-plans/) for local services.

As I said with #789 the best way to raise any future issues like this is through the "Is there anything wrong with this page?" link at the bottom of the page. Thanks for raising this though.
