### ISSUE TITLE
Error on postcode should reshow postcode

### ISSUE THREAD

**Issue by dracos** [alphagov/frontend#789]
If a postcode is entered that is not recognised on e.g. https://www.gov.uk/report-pothole, the postcode field is blanked out. If the issue was simply a typo, or a misspelling of "5" as "S" or similar, it is annoying that you cannot see and correct the problem directly, but have to start again.

**Comment by RosalynV** [comment]
Thanks for raising this issue. I've logged it in the relevant [improvement plan](https://insidegovuk.blog.gov.uk/2015/03/13/introducing-improvement-plans/) for local services, we'll consider it when we look at improving the local services as a whole.

The best way to raise issues like this is through the "Is there anything wrong with this page?" link at the bottom of each page. That raises a ticket with our support desk who can then record it, link it to any similar reports and make sure they get to the relevant team.

**Comment by dracos** [comment]
If you're not using issues on this repository, you can turn them off in the repository admin (and let people know where to raise issues in the README) :-) I do think a public facing list of issues is nicer than a private reporting link into an unknown system, though – you can see the issue is already made (or not), for one thing, presumably potentially saving you time of many people reporting the same thing...
